In [18]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import OneHotEncoder

In [19]:
from sklearn.pipeline import Pipeline
from sklearn.linear_model import SGDRegressor
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    mean_squared_error,
    r2_score
)


Load the House Price dataset and display:
- Dataset shape
- First 10 rows
- 5 random samples

In [20]:
# Question 1
df=pd.read_csv("house_price_regression_dataset.csv")
display(df.shape)
display(df.head(10))

(1000, 8)

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
0,1360,2,1,1981,0.599637,0,5,2.623829e+05
1,4272,3,3,2016,4.753014,1,6,9.852609e+05
2,3592,1,2,2016,3.634823,0,9,7.779774e+05
3,966,1,2,1977,2.730667,1,8,2.296989e+05
4,4926,2,1,1993,4.699073,0,8,1.041741e+06
5,3944,5,3,1990,2.475930,2,8,8.797970e+05
6,3671,1,2,2012,4.911960,0,1,8.144279e+05
7,3419,1,1,1972,2.805281,1,1,7.034131e+05
8,630,3,3,1997,1.014286,1,8,1.738750e+05
9,2185,4,2,1981,3.941604,2,5,5.041765e+05

In [21]:
display(df.sample(5))

,Square_Footage,Num_Bedrooms,Num_Bathrooms,Year_Built,Lot_Size,Garage_Size,Neighborhood_Quality,House_Price
370,2131,3,1,1959,4.948347,1,6,457643.098042
441,3002,5,2,2014,2.440006,0,4,690243.750686
135,3945,5,3,2000,2.368584,1,8,860329.492311
619,3332,5,2,1962,1.751448,2,2,704212.523977
486,2310,5,1,2011,0.770434,1,3,523323.067060

## Question 5 (20 Marks)

Build a complete **Pipeline** using Scikit-Learn that includes:
- The `ColumnTransformer`
- `SGDRegressor` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [22]:
# Question 5
X = df.drop(
    "House_Price",
    axis=1
)

y = df["House_Price"]

In [23]:
X_train,X_test,y_train,y_test=train_test_split(
    X,y,test_size=0.2,random_state=42
)

In [24]:
numerical_features = [
    "Square_Footage",
    "Num_Bedrooms",
    "Num_Bathrooms"
]

categorical_features = [
    "Neighborhood_Quality"
]

In [25]:
preprocessor=ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features

         ),
        (
            "cat",
            OneHotEncoder(),
            categorical_features
        ),

    ],
    remainder="passthrough"
)

In [26]:
pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),

        (
            "model",
            SGDRegressor(
                random_state=42
            )
        )
    ]
)

In [27]:
pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['Square_Footage',
                                                   'Num_Bedrooms',
                                                   'Num_Bathrooms']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Neighborhood_Quality'])])),
                ('model', SGDRegressor(random_state=42))])

In [28]:
y_pred = pipeline.predict(
    X_test
)

In [29]:
rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred
    )
)

In [30]:
r2 = r2_score(
    y_test,
    y_pred
)

In [31]:
print("RMSE :", rmse)

print("R² Score :", r2)

RMSE : 2831534044692389.5
R² Score : -1.2438298487868914e+20

In [32]:
print(
    "\nFirst 10 Predictions:\n"
)

for i in range(10):

    print(
        f"Actual: {y_test.iloc[i]:.2f}"
        f" | Predicted: {y_pred[i]:.2f}"
    )

First 10 Predictions:

Actual: 901000.49 | Predicted: -2875535038946872.50
Actual: 494537.51 | Predicted: -2835259072044027.00
Actual: 949404.20 | Predicted: -2798791871199435.00
Actual: 1040389.05 | Predicted: -2813703306771020.00
Actual: 794010.02 | Predicted: -2844984615854858.50
Actual: 724033.56 | Predicted: -2801523053519088.00
Actual: 998439.24 | Predicted: -2852176035949776.50
Actual: 909713.44 | Predicted: -2840682264034587.00
Actual: 792681.52 | Predicted: -2837466460238756.50
Actual: 947490.78 | Predicted: -2856448416944616.50

---
## Question 6 (20 Marks)

Implement **Multiple Linear Regression** using **Scikit-Learn**:
- The `ColumnTransformer`
- `LinearRegression` as the final estimator
- Train the pipeline and evaluate using RMSE and R² score
- Print predicted vs actual values for the first 10 test samples

In [33]:
# Question 6
X = df.drop(
    "House_Price",
    axis=1
)

y = df["House_Price"]

In [34]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [35]:
numerical_features = [
    "Square_Footage",
    "Num_Bedrooms",
    "Num_Bathrooms"
]

categorical_features = [
    "Neighborhood_Quality"
]

In [36]:
preprocessor = ColumnTransformer(
    transformers=[
        (
            "num",
            StandardScaler(),
            numerical_features
        ),

        (
            "cat",
            OneHotEncoder(),
            categorical_features
        )
    ],
    remainder="passthrough"
)

In [37]:
pipeline = Pipeline(
    steps=[
        (
            "preprocessor",
            preprocessor
        ),

        (
            "model",
            LinearRegression()
        )
    ]
)

In [38]:
pipeline.fit(
    X_train,
    y_train
)

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('num', StandardScaler(),
                                                  ['Square_Footage',
                                                   'Num_Bedrooms',
                                                   'Num_Bathrooms']),
                                                 ('cat', OneHotEncoder(),
                                                  ['Neighborhood_Quality'])])),
                ('model', LinearRegression())])

In [39]:
y_pred = pipeline.predict(
    X_test
)

In [40]:
rmse = np.sqrt(
    mean_squared_error(
        y_test,
        y_pred
    )
)

In [41]:
r2 = r2_score(
    y_test,
    y_pred
)

In [42]:
print("RMSE :", rmse)

print("R² Score :", r2)

RMSE : 10250.310447408401
R² Score : 0.9983699856153558

In [ ]:
print(
    "\nFirst 10 Predictions:\n"
)

for i in range(10):

    print(
        f"Actual: {y_test.iloc[i]:.2f}"
        f" | Predicted: {y_pred[i]:.2f}"
    )

First 10 Predictions:

Actual: 901000.49 | Predicted: 869874.44
Actual: 494537.51 | Predicted: 493008.02
Actual: 949404.20 | Predicted: 943543.85
Actual: 1040389.05 | Predicted: 1032332.24
Actual: 794010.02 | Predicted: 776180.75
Actual: 724033.56 | Predicted: 733011.80
Actual: 998439.24 | Predicted: 992374.77
Actual: 909713.44 | Predicted: 885753.69
Actual: 792681.52 | Predicted: 796210.76
Actual: 947490.78 | Predicted: 932031.03